<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ppy.SDL3-CS" Version="2026.520.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Thermal\Thermal.csproj" />
    <ProjectReference Include="..\GreenPng\GreenPng.csproj" />
  </ItemGroup>

</Project>
